### ISSUE TITLE
Finish moving the project to CMake

### ISSUE THREAD

**Issue by friendlyanon** [jk-jeon/dragonbox#4]
Related: https://github.com/jk-jeon/dragonbox/pull/3#issuecomment-698621434

- [ ] Describe the purpose of `benchmark`
- [ ] Make test .cpp sources independent to register each for its own test
- [ ] Remove VS specific files (VS supports CMake)
- [ ] Group various non-code assets in one folder and/or remove from version control (would be nice, root is messy)

**Comment by jk-jeon** [comment]
May I ask you for some suggestions? Because, many "tests" in the test directory are not really tests. What do you think?

- Some of them (`verify_log_computation.cpp`, `verify_cache_length.cpp`, and `verify_fast_multiplication.cpp`) are for verification of various claims written in the paper with explanations like "this can be exhaustively verified". Thus, they are sort of computer-assisted proofs of some mathematical propositions rather than "tests" for finding implementation mistakes. Should I still call them "tests", or something else? Maybe `verify_log_computation.cpp` can be called a unit test because it tests correctness of some subroutines, which is in this case exactly the thing the paper is claiming. (More precisely, it computes the bound on input that the said subroutines can handle correctly.)

- `generate_cache.cpp` and `generate_compressed_cache_error_table.cpp` are even really not tests; they literally generate the magic number arrays used in the algorithm and write them in several text files. So they are in fact some form of meta-programs.

- `perf_test.cpp` is also not really a test. It just runs the whole routine with randomized inputs and never does anything else. Its purpose was to profile the performance and to obtain some (micro)optimization ideas.

- `verify_magic_division.cpp` is an exhaustive unit test of some subroutines ([this](https://github.com/jk-jeon/dragonbox/blob/master/include/dragonbox/dragonbox.h#L682) and [this](https://github.com/jk-jeon/dragonbox/blob/master/include/dragonbox/dragonbox.h#L722)), and `test_all_shorter_interval_cases.cpp` is the exhaustive test of the whole routine for some special sort of inputs.

- `uniform_random_test.cpp` is the randomized test of the whole routine (against the output generated by Ryu), so it is really a test.

- `live_test.cpp` is an interactive program that asks the user to input a floating-point number and then shows the string generated by the library. Its main purpose was for debugging; whenever the random test found some input that Dragonbox failed to handle correctly, I copied that input somewhere and then ran the live test with that input and looked at what's happening with the debugger. I'm not sure if this is really a "test" in the usual sense.

- `misc_test.cpp` only contains an empty function. I used this file whenever I wanted to check something about the algorithm/code instantaneously but didn't want to isolate that into a separate file. Will it be better to leave it only on my local repo and remove it from the public repo?

**Comment by friendlyanon** [comment]
You can namespace tests with proper naming, e.g. `add_test(NAME verification.cache_length ...)` will be called with `ctest -R 'verification.' ...`, so I think that's one solution for your problems. This way it's easy to exclude them from local tests with `-E` flag instead of `-R`, but still have them in CI to make extra sure things don't break.  
Unfortunately there is no `EXCLUDE_FROM_ALL` equivalent for `add_test`.

For other things that aren't really tests I guess you can move them to `subproject/live_test` and `subproject/generate_cache` folders in the root, since they are tightly coupled to the project, but aren't really deserving their own repositories.

**Comment by jk-jeon** [comment]
Sounds good. Another issue is that benchmark code wants to include `random_float.h` which now lives in `test/include` directory. What about to make a directory `subproject` folder in the root and put `test` and `benchmark` folders there, and make a single `subproject/include` folder that every subproject shares?

**Comment by friendlyanon** [comment]
Well, benchmarks are sort of tests. You can namespace them as well and just exclude them with a `-E` flag.

**Comment by jk-jeon** [comment]
I think I finished the 1st version of clean-up. I just have put everything inside `subprojects` directory. Here are some notes:

- There is an `include` directory inside `subprojects`, which all of the subprojects share.
- The `results` directory is where text files generated by some subprojects are written. There is no source file there.
- Each folder other than `3rdparty`, `include`, and `results` corresponds to an independent subproject.
- All of these subprojects except for `benchmark` have only one source file (`main.cpp`).
- `test_all_shorter_interval_cases` and `uniform_random_test` are depending on `3rdparty/ryu`, because they are testing Dragonbox against Ryu. Hence, `3rdparty` should be provided as an include directory.
- `benchmark` is depending on `3rdparty/grisu_exact`, `3rdparty/ryu`, and `3rdparty/schubfach`. I'm not sure which one is better between building them as (static) libraries or just including their source files as build targets. Ryu is shared with some of other subprojects, so it might be better to make it a library, but the other two are only used by `benchmark`.
- I think we can group `compute_required_cache_length`, `test_all_shorter_interval_cases`, `uniform_random_test`, `verify_compressed_cache`, `verify_fast_multiplication`, `verify_log_computation`, and `verify_magic_division` as `test`, and `generate_cache` and `generate_compressed_cache_error_table` as `meta`.
- I didn't remove VS proj/sln files yet as I don't have CMakeLists.txt for subprojects yet. (Current VS proj/sln files are broken; it only contains the main library, 3rd parties, and benchmark.)

**Comment by friendlyanon** [comment]
Just a nit, but I think it should be `subproject` singular.

I can see a tree like this work out well:

    subproject
    ├── benchmark
    │   ├── ...
    │   └── CMakeLists.txt
    ├── common
    │   ├── ...
    │   └── CMakeLists.txt
    ├── meta
    │   ├── ...
    │   └── live_test
    │       ├── ...
    │       └── CMakeLists.txt
    └── test
        ├── ...
        └── CMakeLists.txt

**Comment by jk-jeon** [comment]
How it looks now?

**Comment by friendlyanon** [comment]
I think those `subproject/test/compute_required_cache_length/main.cpp` files should be moved like so: `subproject/test/source/compute_required_cache_length.cpp`  
Similarly for the rest as well.

Since `subproject` is where all the subprojects go, the C++ ones should follow the usual structure like so:

    subproject
    ├── ...
    └── <subproject>
        ├── include # if needed
        ├── source
        │   └── *.cpp
        └── CMakeLists.txt

**Comment by jk-jeon** [comment]
Let me clarify a bit more. So, that another subproject directory lives together with those benchmark, meta, common, and test directories? Also, where should I put 3rd party dependencies?

**Comment by friendlyanon** [comment]
`subproject` is the folder that houses subprojects. `test` is a subproject, `common` is a subproject other subprojects depend on, `meta` is a dependent and a subproject, etc.

Ideally, those 3rd parties would support clients using CMake, but it doesn't look like it.  
From the look of it only `benchmark` uses them, so they should go somewhere in it.

**Comment by jk-jeon** [comment]
I mean, I thought you suggested to make another directory with the name `subproject` inside the `subproject` directory:
> ```
> subproject
> ├── ...
> └── <subproject>
>     ├── include # if needed
>     ├── source
>     │   └── *.cpp
>     └── CMakeLists.txt
> ```

And along with `benchmark`, `uniform_random_test` also relies on Ryu because it is testing the output against Ryu. But others don't depend on any of the 3rd parties.
